requirements.txt able to build a working pyenv on Sherlock
*if* one installs the packages this way:
`CVXOPT_BUILD_GLPK=1 pip install -r requirements.txt --no-binary cvxopt`

I’m close to getting this working on macOS. The small tests give
several errors like this:
>   File
"/Users/jerry/dev/wcEcoli/wholecell/utils/_netflow/nf_glpk.py", line
17, in __init__
>     self._model = glpk.glpk()
> TypeError: __init__() should return None, not 'NoneType'

which suggests problems accessing GLPK, and one like this

> Traceback (most recent call last):
>   File
"/Users/jerry/dev/wcEcoli/wholecell/tests/utils/test_mc_complexation.py"
, line 97, in test_mccFormComplexesWithPrebuiltMatrices
>     updatedMoleculeCounts == expected_updatedMoleculeCounts[i]
> AssertionError: False is not true

caused by who knows what.