a small tweak and now 2 sim gens run in PY3!
Convert a single-element ndarray to an int in order to use it in a numpy shape without the :

    TypeError: only integer scalar arrays can be converted to a scalar index